---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 194453983284.dkr.ecr.ap-northeast-2.amazonaws.com/nginximage:5.0
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m 
        volumeMounts:
        - name: persistent-storage
          mountPath: /static
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-nginx
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 50
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
spec:
  schedule: "0 0 */8 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: nginx
            image: 194453983284.dkr.ecr.ap-northeast-2.amazonaws.com/nginximage:latest
            resources:
              limits:
                cpu: 100m
              requests:
                cpu: 50m
            volumeMounts:
            - name: persistent-storage
              mountPath: /static
          volumes:
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: efs-claim
          restartPolicy: OnFailure
