apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 3
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: 194453983284.dkr.ecr.ap-northeast-2.amazonaws.com/nginximage:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: persistent-storage
          mountPath: /static
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: efs-claim
